#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    
        key=arr[-1]
        while key<arr[n-2]:
            if key<arr[n-2]:
                arr[n-1]=arr[n-2]
                print(*arr)
            n=n-1
        arr[n-1]=key
        print(*arr)
       
           

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
